version: '2.0'
services:
  web:
    build: './'
    ports: 
      - "3000:3000"
    environment:
      - PORT=3000
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./front/public:/srv/www/static
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
