service: just1s-frontend

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'development'}
  region: ap-northeast-1

custom:
  webpack:
    webpackConfig: "vue.config.js"
  serviceDomain:
    development: dev.just1s.xyz
    production: www.just1s.xyz
  serviceApiEndPoint:
    development: dev-api.just1s.xyz
    production: api.just1s.xyz
  serverless-layers:
    functions:
      - main
    dependenciesPath: ./package.json
    layersDeploymentBucket: just1s-frontend-node-module
  # customDomain:
  #   domainName: ${self:custom.serviceDomain.${self:provider.stage}}
  #   stage: ${opt:stage, 'development'}
  #   certificateName: "*.just1s.xyz"
  #   endpointType: "regional"
  #   createRoute53Record: true
  #   securityPolicy: tls_1_2
  #   apiType: rest
  #   autoDomain: false
  #   hostedZoneId: Z02288121UT1NKWXB7B5M

functions:
  main:
    handler: serverless.handler
    events:
      - http:
          cors: true
          path: "/"
          method: any
      - http:
          cors: true
          path: "{proxy+}"
          method: any

plugins:
  - serverless-layers
  - serverless-webpack
  - serverless-offline
  - serverless-domain-manager
