name: Deploy to Development
on:
  push:
    branches:
      - development

jobs:
  always_run:
    name: Always Run
    runs-on: ubuntu-latest
    steps:
      - name: Check inputs
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"

  build_vue:
    name: Build Vue
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
#       - name: setup node
#         uses: actions/setup-node@v1
#         with:
#           node-version: "12"

#       - name: Cache node modules
#         uses: actions/cache@v2
#         with:
#           path: |
#             **/node_modules
#           key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}

#       - name: npm install
#         run: npm install

#       - name: Install Serverless Framework
#         run: npm run build:development

#       - name: Deploy Lambda functions
#         run: sls deploy --stage development

#       - name: Configure AWS credentials
#         uses: aws-actions/configure-aws-credentials@v1
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: ap-northeast-2

#       - name: sync to s3
#         run: |
#         aws s3 sync ./dist s3://dev.just1s.xyz
