name: Deploy to Production
on:
  push:
    branches:
      - master
jobs:
  build_vue:
    name: Build Vue
    runs-on: ubuntu-latest
    env:
      NODE_ENV: "production"
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.OS }}-master-build-${{ hashFiles('**/package-lock.json') }}

      - name: npm install
        run: npm install

      - name: Build
        run: npm run build:production
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      - name: sync to s3 exclude js
        run: aws s3 sync ./dist s3://www.just1s.xyz --exclude "*.js*" --delete

      - name: sync to s3 js with disabled cache
        run: aws s3 sync ./dist s3://www.just1s.xyz --exclude "*" --include "*.js*" --metadata-directive COPY --cache-control max-age=0,no-cache,no-store,must-revalidate --delete