name: Common
on: push

jobs:
  always_run:
    name: Always Run
    runs-on: ubuntu-latest
    steps:
      - name: Check inputs
        run: |
        echo github.ref is: ${{ github.ref }}
        echo github.event_name is: ${{ github.event_name }}
